name: "Where Have They Been"
permalink: pretty
author: Kennedy
email: kennedysgarage@gmail.com
url:
baseurl: /whtb2016

exclude: ["CNAME","editorconfig.txt","Gemfile","Gemfile.lock","README.md", "RAKEFILE"]
